name: Parallel programm

on:
  push:
    branches: [ "dev-branch" ]
  pull_request:
    branches: [ "dev-branch" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++ make cmake  

      - name: Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -S . -B build
          cmake --build build
          sudo cmake --install build  # Installs gtest globally
    
      - name: Build 
        run: 
          make  # Сборка
      - name: Tests
        run:
          make test
